### ISSUE TITLE
Mobile version

### ISSUE THREAD

**Issue by handshake-enthusiast** [ryanmmoon/dir.ectory#2]
From https://github.com/opensystm/handshake-micro-grants/issues/6:  
>Completion Criteria
>
>6. Ensure the user experience is elegent for both mobile and desktop enviornments

Do you plan to improve the mobile version?  
![dir.ectory mobile version](https://github.com/ryanmmoon/dir.ectory/assets/104037912/88cea297-2353-4249-b5b7-04a0929f088e)

**Comment by ryanmmoon** [comment]
Yes, This is being actively worked on and should be updated in couple of weeks.

**Comment by ryanmmoon** [comment]
dir.ectory has finally been optimized for mobile devices. Still some minor things to change, but works for now.
