### ISSUE TITLE
Additional domain redirects

### ISSUE THREAD

**Issue by handshake-enthusiast** [ryanmmoon/dir.ectory#3]
From https://github.com/opensystm/handshake-micro-grants/issues/6:  
> I'll also redirect a few names to dir.ectory for ease of use.
> https://hns.directory/ --> https://dir.ectory/
> https://shakedirectory/ --> https://dir.ectory/
> https://shakespace/ --> https://dir.ectory/

https://hns.directory/ and https://dir.ectory/ are clearly different websites, I suppose it's intended.  
https://shakedirectory/ and https://shakespace/ seem to be not redirecting:  

```
$ dig @139.144.68.241 shakedirectory +short
44.235.163.135

$ dig @139.144.68.241 shakespace +short
44.235.163.135

$ dig @139.144.68.241 dir.ectory +short
45.32.161.14
```

```
$ curl -o /dev/null -s -w "%{http_code}\n" --insecure https://dir.ectory
200

$ curl -o /dev/null -s -w "%{http_code}\n" --insecure https://shakedirectory/ 
000

$ curl -o /dev/null -s -w "%{http_code}\n" --insecure https://shakespace/ 
000
```

**Comment by ryanmmoon** [comment]
The redirects are setup within Namebase. 

It seems they are http only. Maybe redirecting using nginx w/ SSL will work better?

![redirect](https://github.com/ryanmmoon/dir.ectory/assets/47227723/9fd2c95f-fabd-42aa-99e0-cd5ac3252e7c)

**Comment by ryanmmoon** [comment]
Redirects are now using nginx with certs and seems to be working better.
